---
version: '3'
services:
  ci_master:
    build:
      context: .
      dockerfile: tools/docker/Dockerfile.master
    container_name: ci_master
  ci_target:
    build:
      context: .
      dockerfile: tools/docker/Dockerfile.target
    container_name: ci_target
